2018-11-01 12:01:00,315 - alarm_data_regular_filter.py - [line:358] - INFO - 报警数据引擎启动！
2018-11-01 12:01:00,344 - alarm_data_regular_filter.py - [line:422] - INFO - 完成一轮调控记录匹配
2018-11-01 12:01:42,334 - alarm_data_regular_filter.py - [line:107] - INFO - 报警KDE计算程序初始化成功！
2018-11-01 12:01:42,334 - alarm_data_regular_filter.py - [line:111] - INFO - checking new alarm data ... 
2018-11-01 12:02:00,505 - alarm_data_regular_filter.py - [line:294] - INFO - # get KdeHisModel succeed!
2018-11-01 12:02:00,515 - alarm_data_regular_filter.py - [line:422] - INFO - 完成一轮调控记录匹配
2018-11-01 12:02:03,338 - alarm_data_regular_filter.py - [line:137] - ERROR - local variable 'time_point' referenced before assignment
2018-11-01 12:02:48,684 - alarm_data_regular_filter.py - [line:358] - INFO - 报警数据引擎启动！
2018-11-01 12:02:48,692 - alarm_data_regular_filter.py - [line:294] - INFO - # get KdeHisModel succeed!
2018-11-01 12:02:48,722 - alarm_data_regular_filter.py - [line:422] - INFO - 完成一轮调控记录匹配
2018-11-01 12:03:30,728 - alarm_data_regular_filter.py - [line:107] - INFO - 报警KDE计算程序初始化成功！
2018-11-01 12:03:30,729 - alarm_data_regular_filter.py - [line:111] - INFO - checking new alarm data ... 
2018-11-01 12:03:48,733 - alarm_data_regular_filter.py - [line:422] - INFO - 完成一轮调控记录匹配
2018-11-01 12:03:51,749 - alarm_data_regular_filter.py - [line:137] - ERROR - local variable 'time_point' referenced before assignment
2018-11-01 12:04:48,742 - alarm_data_regular_filter.py - [line:422] - INFO - 完成一轮调控记录匹配
2018-11-01 12:04:51,750 - alarm_data_regular_filter.py - [line:111] - INFO - checking new alarm data ... 
2018-11-01 12:05:12,752 - alarm_data_regular_filter.py - [line:137] - ERROR - local variable 'time_point' referenced before assignment
2018-11-01 13:04:03,589 - alarm_data_regular_filter.py - [line:377] - INFO - 报警数据引擎启动！
2018-11-01 13:04:03,589 - alarm_data_regular_filter.py - [line:377] - INFO - 报警数据引擎启动！
2018-11-01 13:04:03,603 - alarm_data_regular_filter.py - [line:313] - INFO - # get KdeHisModel succeed!
2018-11-01 13:04:03,603 - alarm_data_regular_filter.py - [line:313] - INFO - # get KdeHisModel succeed!
2018-11-01 13:04:45,608 - alarm_data_regular_filter.py - [line:111] - INFO - 报警KDE计算程序初始化成功！
2018-11-01 13:04:45,608 - alarm_data_regular_filter.py - [line:111] - INFO - 报警KDE计算程序初始化成功！
2018-11-01 13:04:45,609 - alarm_data_regular_filter.py - [line:115] - INFO - checking new alarm data ... 
2018-11-01 13:04:45,609 - alarm_data_regular_filter.py - [line:115] - INFO - checking new alarm data ... 
2018-11-01 13:04:45,624 - SituationOperate.py - [line:198] - ERROR - 数据库连接失败！
2018-11-01 13:04:45,624 - SituationOperate.py - [line:198] - ERROR - 数据库连接失败！
2018-11-01 13:04:45,625 - alarm_data_regular_filter.py - [line:442] - INFO - 完成一轮调控记录匹配
2018-11-01 13:04:45,625 - alarm_data_regular_filter.py - [line:442] - INFO - 完成一轮调控记录匹配
2018-11-01 13:05:06,639 - alarm_data_regular_filter.py - [line:144] - ERROR - local variable 'time_point' referenced before assignment
2018-11-01 13:05:06,639 - alarm_data_regular_filter.py - [line:144] - ERROR - local variable 'time_point' referenced before assignment
2018-11-01 13:05:45,642 - SituationOperate.py - [line:198] - ERROR - 数据库连接失败！
2018-11-01 13:05:45,642 - SituationOperate.py - [line:198] - ERROR - 数据库连接失败！
2018-11-01 13:05:45,643 - alarm_data_regular_filter.py - [line:442] - INFO - 完成一轮调控记录匹配
2018-11-01 13:05:45,643 - alarm_data_regular_filter.py - [line:442] - INFO - 完成一轮调控记录匹配
2018-11-01 13:06:06,640 - alarm_data_regular_filter.py - [line:115] - INFO - checking new alarm data ... 
2018-11-01 13:06:06,640 - alarm_data_regular_filter.py - [line:115] - INFO - checking new alarm data ... 
